# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default  # This uses your self-hosted agent running on your VM

steps:

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'vm-ssh-new'  # Replace this with your exact SSH service connection name
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/home/azureagent/azure_vm_manager'

- task: SSH@0
  inputs:
    sshEndpoint: 'vm-ssh-new'  # Same SSH service connection name
    runOptions: 'commands'
    commands: |
      cd /home/azureagent/azure_vm_manager
      python3 azure_vm_manager.py
