# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'vm-ssh-new'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/home/azureuser/azure_vm_manager'

- task: SSH@0
  inputs:
    sshEndpoint: 'vm-ssh-new'
    runOptions: 'commands'
    commands: |
      cd /home/azureuser/azure_vm_manager
      ls
      python3 azure.py

